### ISSUE TITLE
Use browser history instead of "Back" button

### ISSUE THREAD

**Issue by anandthakker** [mapbox/flamebearer#2]
I keep wanting to hit Cmd-Back to get back to the previous view.  Using a url hash, this would be possible, and could have the added benefit of allowing you to share a link directly to a specific part of the timeline.

**Comment by mourner** [comment]
Agreed, that would be nice!

**Comment by mourner** [comment]
Small question, — should a "Reset" push a new history state, or go back to the original one (page load)?

**Comment by anandthakker** [comment]
Maybe "Reset" could be dropped in favor of just reloading the page?
