### ISSUE TITLE
The third command gets stuck. Generates no output file.

### ISSUE THREAD

**Issue by iamnewspecies** [mapbox/flamebearer#9]
Wen I execute this command `node --prof-process --preprocess -j isolate*.log | flamebearer`. It just does something and hangs (no response for infinitely long time). Are there cases when this can happen?

**Comment by mourner** [comment]
Does `node --prof-process --preprocess -j isolate*.log` completele on its own (without flamebearer)?

**Comment by iamnewspecies** [comment]
`node --prof-process --preprocess -j isolate*.log` does not complete on its own. 
Following is the log file:
https://gist.github.com/iamnewspecies/233c72ec6dcbbd71e64ba63d0617209c

**Comment by mourner** [comment]
Does not? Should be a Node bug then?
